[project]
name = "pyG12"
version = "0.1.1"
description = "Pacote exemplo que mostra uma janelinha"
authors = [{ name = "Davi10556" }]
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
pyG12 = "pyG12.main:main"
